Add build of Octave with GUI functionality.

diff --git a/Dockerfile.gui b/Dockerfile.gui
--- a/Dockerfile.gui
+++ b/Dockerfile.gui
@@ -8,6 +8,7 @@ LABEL maintainer="Jonathan Goldfarb <jgoldfar@my.fit.edu>"
 RUN apt-get -qq -y update && \
     apt-get -q -y --no-install-recommends install \
       build-essential \
+      libgfortran-6-dev \
       # Following two needed for curl dependency in Octave build
       curl \
       libcurl4-openssl-dev \
@@ -91,10 +92,12 @@ RUN mkdir -p ${OctavePath} && \
 RUN patch -p0 < getcwd-path-max.patch && \
     cd ${OctavePath} && \
     autoreconf -i -f && \
-    ./configure && \
+    ./configure --disable-docs && \
     make -j3 install && \
-    ( make check || echo "Tests Failed." ) && \
-    apt-get -qq -y remove \
+    ( make check || echo "Tests Failed." )
+
+RUN apt-get -qq -y remove \
+      build-essential \
       patch \
       curl \
       autoconf \
@@ -131,34 +134,41 @@ RUN apt-get -qq -y update && \
       texinfo \
       ghostscript \
       gnuplot \
-      #
+      # Build-essential related
+      libgomp1 \
+      libcurl4-openssl-dev \
+      libgfortran-6-dev \
+      libhdf5-serial-dev \
+      libquadmath0 \
+      libqhull7 \
+      # Linear Algebra
+      libsuitesparseconfig4 \
+      # AMD
       libamd2 \
       libcamd2 \
       libcolamd2 \
       libccolamd2 \
-      #
+      # Other LA
       libumfpack5 \
       libqrupdate1 \
       libcholmod3 \
       libarpack2 \
       libopenblas-base \
       libcxsparse3 \
-      #
+      # FFTW
       libfftw3-double3 \
       libfftw3-single3 \
-      #
+      # Graphical Output
       libfltk-gl1.3 \
       libfltk1.3 \
       libfontconfig1 \
       libfreetype6 \
+      libgl2ps1 \
       libgl1-mesa-glx \
-      #
-      libglpk40 \
       libglu1-mesa \
-      #
-      libgomp1 \
       libosmesa6 \
-      libqhull7 \
+      # CLI
+      libreadline7 \
       # QT
       libqscintilla2-12v5 \
       libqtcore4 \
@@ -176,7 +186,7 @@ COPY --from=builder /usr/local/share/octave /usr/local/share/octave
 
 # Copy over Octave binaries (includes mkoctfile)
 COPY --from=builder /usr/local/bin/*oct* /usr/local/bin/
-
+COPY --from=builder /usr/local/libexec/octave/${OctaveVersion} /usr/local/libexec/octave/
 # Copy over Octave docstrings. Note that some paths contain 
 # version-specific information.
 COPY --from=builder /usr/local/share/octave/${OctaveVersion}/etc/built-in-docstrings /usr/local/share/octave/${OctaveVersion}/etc/
@@ -193,8 +203,7 @@ COPY --from=builder /usr/local/share/octave/${OctaveVersion}/m /usr/local/share/
 # Copy over Octave site packages
 COPY --from=builder /usr/local/share/octave/site/* /usr/local/share/octave/site/
 
-# Copy over Manfiles
-COPY --from=builder /usr/local/share/man/man1/*oct* /usr/local/share/man/man1/
+# NOTE: Manfiles and docs not copied because they weren't built!
 
 # Copy all other dylibs needed to run octave, starting with those
 # linked into liboctave or directly into the octave executable
@@ -205,14 +214,14 @@ COPY --from=builder /usr/local/share/man/man1/*oct* /usr/local/share/man/man1/
 
 #
 #COPY --from=builder /usr/lib/x86_64-linux-gnu/libgomp.so.1 /usr/lib/x86_64-linux-gnu/
-COPY --from=builder /usr/lib/x86_64-linux-gnu/libhdf5_serial.so.100 /usr/lib/x86_64-linux-gnu/
+#COPY --from=builder /usr/lib/x86_64-linux-gnu/libhdf5_serial.so.100 /usr/lib/x86_64-linux-gnu/
 #COPY --from=builder /usr/lib/x86_64-linux-gnu/libfftw3f_threads.so.3 /usr/lib/x86_64-linux-gnu/
 #COPY --from=builder /usr/lib/x86_64-linux-gnu/libfftw3_threads.so.3 /usr/lib/x86_64-linux-gnu/
 #COPY --from=builder /usr/lib/x86_64-linux-gnu/libfftw3f.so.3 /usr/lib/x86_64-linux-gnu/
 #COPY --from=builder /usr/lib/x86_64-linux-gnu/libfftw3.so.3 /usr/lib/x86_64-linux-gnu/
 #COPY --from=builder /usr/lib/x86_64-linux-gnu/libGLU.so.1 /usr/lib/x86_64-linux-gnu/
-COPY --from=builder /usr/lib/x86_64-linux-gnu/libgl2ps.so.1 /usr/lib/x86_64-linux-gnu/
-COPY --from=builder /usr/lib/x86_64-linux-gnu/libcurl.so.4 /usr/lib/x86_64-linux-gnu/
+#COPY --from=builder /usr/lib/x86_64-linux-gnu/libgl2ps.so.1 /usr/lib/x86_64-linux-gnu/
+#COPY --from=builder /usr/lib/x86_64-linux-gnu/libcurl.so.4 /usr/lib/x86_64-linux-gnu/
 #COPY --from=builder /usr/lib/x86_64-linux-gnu/libcholmod.so.3 /usr/lib/x86_64-linux-gnu/
 #COPY --from=builder /usr/lib/x86_64-linux-gnu/libumfpack.so.5 /usr/lib/x86_64-linux-gnu/
 #COPY --from=builder /usr/lib/x86_64-linux-gnu/libamd.so.2 /usr/lib/x86_64-linux-gnu/
@@ -220,12 +229,13 @@ COPY --from=builder /usr/lib/x86_64-linux-gnu/libcurl.so.4 /usr/lib/x86_64-linux
 #COPY --from=builder /usr/lib/x86_64-linux-gnu/libcolamd.so.2 /usr/lib/x86_64-linux-gnu/
 #COPY --from=builder /usr/lib/x86_64-linux-gnu/libccolamd.so.2 /usr/lib/x86_64-linux-gnu/
 #COPY --from=builder /usr/lib/x86_64-linux-gnu/libcxsparse.so.3 /usr/lib/x86_64-linux-gnu/
-COPY --from=builder /usr/lib/x86_64-linux-gnu/libsuitesparseconfig.so.4 /usr/lib/x86_64-linux-gnu/
+#COPY --from=builder /usr/lib/x86_64-linux-gnu/libsuitesparseconfig.so.4 /usr/lib/x86_64-linux-gnu/
 #COPY --from=builder /usr/lib/x86_64-linux-gnu/libqrupdate.so.1 /usr/lib/x86_64-linux-gnu/
-COPY --from=builder /usr/lib/x86_64-linux-gnu/libreadline.so /usr/lib/x86_64-linux-gnu/
-COPY --from=builder /lib/x86_64-linux-gnu/libreadline.so.7 /lib/x86_64-linux-gnu/
-COPY --from=builder /usr/lib/x86_64-linux-gnu/libgfortran.so.3 /usr/lib/x86_64-linux-gnu/
-COPY --from=builder /usr/lib/x86_64-linux-gnu/libquadmath.so.0 /usr/lib/x86_64-linux-gnu/
+#COPY --from=builder /usr/lib/x86_64-linux-gnu/libreadline.so /usr/lib/x86_64-linux-gnu/
+#COPY --from=builder /lib/x86_64-linux-gnu/libreadline.so.7 /lib/x86_64-linux-gnu/
+#COPY --from=builder /usr/lib/x86_64-linux-gnu/libgfortran.so.3 /usr/lib/x86_64-linux-gnu/
+#COPY --from=builder /usr/lib/x86_64-linux-gnu/libquadmath.so.0 /usr/lib/x86_64-linux-gnu/
+
 COPY --from=builder /usr/lib/x86_64-linux-gnu/libnghttp2.so.14 /usr/lib/x86_64-linux-gnu/
 COPY --from=builder /usr/lib/x86_64-linux-gnu/libidn2.so.0 /usr/lib/x86_64-linux-gnu/
 COPY --from=builder /usr/lib/x86_64-linux-gnu/librtmp.so.1 /usr/lib/x86_64-linux-gnu/
@@ -249,6 +259,24 @@ COPY --from=builder /usr/lib/libGraphicsMagick-Q16.so.3 /usr/lib/
 # Not linked anywhere (?)
 #COPY --from=builder /usr/lib/x86_64-linux-gnu/libqhull.so.7 /usr/lib/x86_64-linux-gnu/
 
+# Install octave package as equiv package
+COPY octave-local.tpl /tmp/octave-equivs/octave-local.tpl
+
+RUN apt-get --no-install-recommends -y install equivs && \
+    cd /tmp/octave-equivs && \
+    equivs-control octave-local && \
+    sed 's/__VER__/${OctaveVersion}/' octave-local.tpl > octave-local && \
+    cat octave-local && \
+    equivs-build octave-local && \
+    ls -lR && \
+    dpkg -i octave-local_*.deb && \
+    apt-get -qq -y remove equivs && \
+    apt-get -qq -y autoremove && \
+    apt-get autoclean && \
+    cd / && \
+    rm -rf \
+      /var/lib/apt/lists/* \
+      /var/log/dpkg.log
 
 ENV DISPLAY :0
 
